### PR TITLE
Changing the initial capital letter on locales

### PR DESCRIPTION
**Pull request by mathfeola**

### CODE REVIEW

**Comment by oscartanner** [comment]
Why change "I" to "i" if "I" is always capital?

**Comment by mathfeola** [comment]
I believe sometimes it looks better on spec.

I can say "Then i am on a page that contains 'something'" instead of "Then I am on a page that contains 'something'"

**Comment by oscartanner** [comment]
Not capital "I" is informal and grammatically wrong, so I can't see why using it would looks better :)

**Comment by mathfeola** [comment]
But the "I" is not the first thing on the scenario =O

**Pull request merged**
